name: Update Nathcrea on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Update Nathcrea on Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} bash -c "
            echo 'Step 1: Navigating to /var/www/nathcrea...';
            cd /var/www/nathcrea &&
            echo 'Step 2: Pulling latest changes...';
            git pull origin main &&
            echo 'Step 3: Clearing cache...';
            php bin/console cache:clear --no-warmup --env=prod &&
            echo 'Step 4: Restarting services...';
            sudo systemctl restart nginx;
          "
