name: Update Nathcrea on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Update Nathcrea on Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} bash -c "
            echo 'Checking /var/www/nathcrea...';
            if [ ! -d /var/www/nathcrea ]; then
              echo 'Directory not found. Cloning repository...';
              git clone https://github.com/***/nathcrea.git /var/www/nathcrea;
            else
              echo 'Directory exists. Pulling updates...';
              cd /var/www/nathcrea &&
              git pull origin main;
            fi &&
            echo 'Checking dependencies...';
            cd /var/www/nathcrea &&
            if [ ! -d vendor ]; then
              echo 'Installing dependencies...';
              composer install --no-interaction --prefer-dist --optimize-autoloader;
            fi &&
            echo 'Clearing cache...';
            php bin/console cache:clear --env=prod &&
            echo 'Restarting services...';
            sudo systemctl restart nginx;
          "
