name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi using sshpass
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} bash -c "
            echo 'Step 1: Checking if /var/www/Nathcrea exists...';
            if [ -d '/var/www/Nathcrea' ]; then
              echo 'Step 2: Directory exists. Proceeding...';
              cd /var/www/Nathcrea;
              echo 'Step 3: Pulling latest changes...';
              git pull origin main;
              echo 'Step 4: Restoring .env...';
              git checkout -- .env;
              echo 'Step 5: Installing dependencies with Composer...';
              composer install --no-interaction --prefer-dist --optimize-autoloader;
              echo 'Step 6: Clearing Symfony cache...';
              php bin/console cache:clear --env=prod;
              echo 'Step 7: Restarting Nginx...';
              sudo systemctl restart nginx;
            else
              echo 'Directory /var/www/Nathcrea does not exist. Exiting.';
              exit 1;
            fi
          "
