name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi using sshpass
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} bash -c "
            set -e # Arrête le script à la première erreur
            echo 'Step 1: Checking if /var/www/Nathcrea exists...'
            if [ ! -d '/var/www/Nathcrea' ]; then
              echo 'Directory /var/www/Nathcrea does not exist. Exiting.';
              exit 1;
            fi;
            
            echo 'Step 2: Navigating to /var/www/Nathcrea...'
            cd /var/www/Nathcrea || exit 1;
            
            echo 'Step 3: Pulling latest changes from Git...'
            git pull origin main || exit 1;
            
            echo 'Step 4: Restoring .env...'
            git checkout -- .env || exit 1;
            
            echo 'Step 5: Running Composer install...'
            composer install --no-interaction --prefer-dist --optimize-autoloader || exit 1;
            
            echo 'Step 6: Clearing Symfony cache...'
            php bin/console cache:clear --env=prod || exit 1;
            
            echo 'Step 7: Restarting Nginx...'
            sudo systemctl restart nginx || exit 1;
          "
