name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi using sshpass
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} bash -c "
            echo 'Step 0: Listing directories in /var/www...';
            ls -la /var/www;
            
            echo 'Step 1: Checking if /var/www/Nathcrea exists...';
            if [ -d '/var/www/Nathcrea' ]; then
              echo 'Directory exists, continuing...';
              cd /var/www/Nathcrea &&
              git pull origin main &&
              git checkout -- .env &&
              composer install --no-interaction --prefer-dist --optimize-autoloader &&
              php bin/console cache:clear --env=prod &&
              sudo systemctl restart nginx;
            else
              echo 'Directory /var/www/Nathcrea does not exist. Exiting.';
              exit 1;
            fi
          "
