name: Deploy Nathcrea to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.SSH_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy application
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
          echo "Starting deployment on Raspberry Pi";

          # Vérification du répertoire
          if [ ! -d /var/www/nathcrea ]; then
            echo "Directory does not exist. Cloning repository...";
            git clone https://github.com/MrLeoufff/nathcrea.git /var/www/nathcrea;
          else
            echo "Directory exists. Pulling latest changes...";
            cd /var/www/nathcrea &&
            echo "Resetting local changes..." &&
            git reset --hard HEAD &&
            echo "Pulling latest changes..." &&
            git pull origin main;
          fi;

          # Vérification et installation des dépendances
          echo "Checking dependencies...";
          cd /var/www/nathcrea &&
          if [ ! -d vendor ]; then
            echo "Installing dependencies...";
            composer install --no-interaction --prefer-dist --optimize-autoloader;
          else
            echo "Dependencies already installed.";
          fi;

          # Effacer le cache
          echo "Clearing cache...";
          php bin/console cache:clear --env=prod;
          echo "Warming up cache..." &&
          php bin/console cache:warmup --env=prod &&
          chmod -R 775 var/ &&
          chown -R www-data:www-data var/ &&

          # Redémarrer les services
          echo "Restarting services...";
          sudo systemctl restart nginx;

          echo "Deployment completed successfully.";
          EOF
